# Generated by Django 5.1 on 2024-09-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Saison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_saison', models.IntegerField()),
                ('date_de_sortie', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_de_sortie', models.DateField()),
                ('duree', models.DurationField()),
                ('image', models.URLField()),
                ('video', models.URLField()),
                ('acteurs', models.CharField(max_length=255)),
                ('producteurs', models.CharField(max_length=255)),
                ('genre', models.ManyToManyField(related_name='films', to='gestion_contenus.genre')),
            ],
        ),
        migrations.CreateModel(
            name='EvenementLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_evenement', models.DateTimeField()),
                ('lien_streaming', models.URLField()),
                ('image', models.ImageField(upload_to='evenements/')),
                ('genre', models.ManyToManyField(related_name='evenements', to='gestion_contenus.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('numero_episode', models.IntegerField()),
                ('duree', models.DurationField()),
                ('video', models.URLField()),
                ('saison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='gestion_contenus.saison')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_de_sortie', models.DateField()),
                ('image', models.URLField()),
                ('genre', models.ManyToManyField(related_name='series', to='gestion_contenus.genre')),
            ],
        ),
        migrations.AddField(
            model_name='saison',
            name='serie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saisons', to='gestion_contenus.serie'),
        ),
    ]
