# Generated by Django 5.1 on 2024-08-29 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utilisateur',
        ),
    ]
