# Generated by Django 5.1 on 2024-09-06 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonnement', '0001_initial'),
        ('paiement', '0002_remove_transaction_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='abonnement.subscription'),
        ),
    ]
